### ISSUE TITLE
Non-canonical splice sites

### ISSUE THREAD

**Issue by mmaitenat** [bioinfo-biols/CIRI-long#10]
Hi again,

I would like CIRI-long not to rely on the canonical GT/AG splice signal only. However, when I run the tool both with and without the `--canonical` argument, the results are the same. If I understood correctly, the `--canonical` option is always set to TRUE. Is it possible to disable it so that non-canonical ones are also considered?

Thanks,

Maitena.

**Comment by Kevinzjy** [comment]
Hi @mmaitenat, the '--canonical' option is not effective. Considering the high-error rate of nanopore reads, it's more appropriate to use defined splicing signals rather than perform de novo alignment. Here's the instructions to modify splice signal sequences in CIRI-long: https://ciri-cookbook.readthedocs.io/en/latest/CIRI-long_2_usage.html#using-non-canonical-splice-signals
